### ISSUE TITLE
Do you have plans to update the plugin? 

### ISSUE THREAD

**Issue by planetahuevo** [Themetry/Pricing-Tables-Pro#1]
I like your approach on this plugin but I cannot trus developments that are left behind for my websites. 

Do you plan to keep this repo and the plugin updated?

Thanks!

**Comment by lelandf** [comment]
If there's a reason to update it, I'll update it. If you're looking for frequent, token updates, another plugin might be a better choice.

**Comment by planetahuevo** [comment]
Your plugin does not say if it has been tested on the latest version of wordpress. 
If it works, you should update it to reflect that. 
For me that is a reason to update.
